### PR TITLE
Help with the new SAMTools website

### PR DESCRIPTION
**Pull request by ewels**
Hi there,

I saw the new SAMTools / HTSlib website today and thought that I might be able to help out a little. You've used a great setup for the website (github hosting + jekyll + bootstrap :+1: ) but were missing out on much of the stuff that these tools give you for free.

I've had a quick whip through and done some redesigning. Specifically:
- Convert most of the pages from HTML to markdown
  - Markdown makes updating much easier, plus styling more consistent. There was quite a lot of broken HTML in these pages (unclosed tags etc) and using Markdown avoids all of this.
- Structure rewrite using bootstrap styles
  - I rewrote the display of the header and homepage using some of the bootstrap components designed for this purpose. _eg._ using glyphicon icons instead of home-written SVG files; navbar component instead of submenu navigation pills.
- One or two new features
  - Highlighting the current page in the navigation
  - Direct call to action (download button) on the homepage
  - Responsive features of bootstrap now work - pages should look good on all screen sizes (_eg._ mobile phones)

Feel free to use as much or as little as you like - creating these pages is one of those things that is "easy when you know how" and can be very frustrating when you don't, so thought that I might be able to save some stress.

The man pages are longer so I thought I'd hold off restructuring these until you'd seen this PR - I'm happy to give them similar treatment if you'd like though. Same goes for making a logo for the home page and actually styling the website - this is fairly trivial if you're interested and don't mind shortcuts using one of the many [free](http://bootswatch.com/) [themes](http://startbootstrap.com/) which are available.

Cheers,

Phil

screen shot 2014-09-08 at 15 10 35
screen shot 2014-09-08 at 15 11 01

### CODE REVIEW

**Comment by tk2** [comment]
Hi Phil,

Thank you for your improvements to the Samtools site, we are keen on pulling them in. One thing we noticed is that on home page, when the browser window is made narrower the boxes don't seem to go from a 1x4 layout to a 2x2 layout?

On the homepage, could you change the 'SAMTools' to 'Samtools' everywhere.

Thanks,
Thomas

**Comment by ewels** [comment]
Hi Thomas,

Glad you like it! What browser are you using? The boxes go to a 2x2 layout for me (Chrome, OSX). I'll have a look to see if I've made any errors. The capitalisation is fixed.

Are there any themes that you like on http://bootswatch.com ? We can drag and drop them in very easily to make it look slightly less like every other website on the web..

Phil

**Comment by ewels** [comment]
..just added an extra line which may fix problems with the 2x2 blocks.

**Comment by tk2** [comment]
Hi Phil - I'm also using Chrome/OSX. That last change you made seems to have almost fixed it - there are now three states (see attached) when reducing the window width.

One other tiny thing - could you change 'Welcome to the new Samtools website' on the landing page to just 'Samtools'?

In terms of themes, we have had a quite nice design submitted to us (currently in jpg format though - see attached) that is on our todo list to convert to css.

Thomas
screen shot 2014-09-15 at 4 31 02 pm
screen shot 2014-09-15 at 4 30 50 pm
screen shot 2014-09-15 at 4 30 36 pm
websamtools-2014-09-15 v2

**Comment by ewels** [comment]
Hi Thomas,

Apologies, additional class added and flow problem fixed. The reason that I couldn't see this is because you're viewing the site through my github account instead of running it locally with Jekyll. Because of the way that the Jekyll config file is written, the `{{ site.baseurl }}` is incorrect at this location and so none of the links work. As such, the CSS file isn't loaded, and things look slightly different. (The Bootstrap CSS is loaded from an external CDN, which is why the page works at all).

Phil

**Comment by tk2** [comment]
I merged your changes.

I was just looking at the site and the site.baseurl doesn't seem to take 
you back to www.htslib.org e.g. the 'Home' button in header.html:

<a href="{{ site.baseurl }}">Home</a>

Thomas

On 9/16/14, 9:02 AM, Phil Ewels wrote:

> Hi Thomas,
> 
> Apologies, additional class added and flow problem fixed. The reason 
> that I couldn't see this is because you're viewing the site through my 
> github account instead of running it locally with Jekyll. Because of 
> the way that the Jekyll config file is written, the |{{ site.baseurl 
> }}| is incorrect at this location and so none of the links work. As 
> such, the CSS file isn't loaded, and things look slightly different. 
> (The Bootstrap CSS is loaded from an external CDN, which is why the 
> page works at all).
> 
> Phil
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/samtools/www.htslib.org/pull/3#issuecomment-55708944.

## 

 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by tk2** [comment]
Fixed now.

Thomas

On 9/16/14, 9:23 AM, Thomas Keane wrote:

> I merged your changes.
> 
> I was just looking at the site and the site.baseurl doesn't seem to 
> take you back to www.htslib.org e.g. the 'Home' button in header.html:
> 
> <a href="{{ site.baseurl }}">Home</a>
> 
> Thomas
> 
> On 9/16/14, 9:02 AM, Phil Ewels wrote:
> 
> > Hi Thomas,
> > 
> > Apologies, additional class added and flow problem fixed. The reason 
> > that I couldn't see this is because you're viewing the site through 
> > my github account instead of running it locally with Jekyll. Because 
> > of the way that the Jekyll config file is written, the |{{ 
> > site.baseurl }}| is incorrect at this location and so none of the 
> > links work. As such, the CSS file isn't loaded, and things look 
> > slightly different. (The Bootstrap CSS is loaded from an external 
> > CDN, which is why the page works at all).
> > 
> > Phil
> > 
> > —
> > Reply to this email directly or view it on GitHub 
> > https://github.com/samtools/www.htslib.org/pull/3#issuecomment-55708944.

## 

 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by ewels** [comment]
Yup - as you saw, it was because baseurl was empty. Your fix works online, but will break local testing. We should be able to use `"/"` instead of `""` and it will work online and offline, plus homepage links will work. I've just tried it locally and it worked.

No rush, I might put in another PR with some homepage styling updates shortly. Also some updates to the man pages. I'll include the change in that.

**Pull request merged**
