### PR TITLE
Navigation simplifcation, homepage style updates

### PR DESCRIPTION
**Pull request by ewels**
- Icons on the homepage are now larger and more colourful
- Navigation is simplified so that it's less broken up
  - Dropdown navigation elements to directly access headings on other pages is maybe a little overkill - I certainly found them a bit confusing
  - I merged the download and develop pages, as develop was basically only a single paragraph.
- Config change to update the `{{base.url}}` to a non-empty string which will work with local and remote testing.
  - Corresponding link updates through the site.

image

### CODE REVIEW

**Comment by tk2** [comment]
We added a new item to the workflow page (and links to it from the homepage and header) after we pulled in your last PR. Is there any chance you could sync your PR with the current version of the site and then I'll merge it in. Thanks for your improvements so far.

**Comment by ewels** [comment]
Hi @tk2 - I had a quick look and your changes were going to make a huge merge conflict with what I'd done. Instead, I just added your new workflow to my changes (with a few styling changes, hope that's ok). If you now revert your recent commits and merge my PR we should have my changes along with your new workflow. Does that make sense? Let me know if you'd like me to do anything differently.

**Comment by ewels** [comment]
Hi there,

I've just pulled in all of your commits to my repo and resolved all of the merge conflicts, so you should be fine to merge this PR with no problems now. If in doubt I went with whatever change you had made, so everything should work. Shout if you have any queries..

Cheers,

Phil

**Comment by jkbonfield** [comment]
Closing as stale.  Sorry we didn't act on this sooner!

**Comment by ewels** [comment]
Wow, this was a blast from the past! 😅 No worries at all!

**Comment by jkbonfield** [comment]
FWIW I do actually like the bigger icons, but the web site has changed so much and I don't think any of us are really up to speed with the intricacies of CSS and portability.  Evidence (8 years of ignoring it!) showed we don't have the bandwidth to act on this sadly.

At times like this though I wish there was a "silently close" option on github. ;-)  /swept-under-carpet

**Comment by ewels** [comment]
Hah, I know the feeling! I have a few of these of my own 👀 No offence taken whatsoever! Feel free to drop me a line if ever you fancy a new website, I'd be happy to help out!

**Pull request closed without merging**
